import type { NextPage } from 'next'
import Head from 'next/head'
import Template from 'components/Template/Template'
import { FirstScreen } from 'sections/FirstScreen/FirstScreen'
import { Cases } from 'sections/Cases/Cases'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Template>
        <FirstScreen />
        <Cases />
      </Template>
    </>
  )
}

export default Home
